CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_BUTTONS=y

# 리포트 지연 줄이기
CONFIG_LOG=n
CONFIG_LOG_MODE_DEFERRED=n

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

CONFIG_ZMK_POINTING_SMOOTH_SCROLL=n
