# 콘솔 출력
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# 로그 시스템
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_DEFAULT_LEVEL=3

# 키 이벤트 로그
CONFIG_ZMK_USB_LOGGING=y

CONFIG_ZMK_LOG_LEVEL_DBG=y

CONFIG_LOG_MAX_LEVEL=4
